name: index
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  colorize_lumberdash: ^3.0.0
  customizable_space_bar: ^0.2.0
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.4.0
  flutter_html: ^2.2.1
  fluttertoast: ^8.1.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  lumberdash: ^3.0.0
  shimmer: ^2.0.0
  sliding_sheet: ^0.5.2
  timeago: ^3.3.0
  url_launcher: ^6.1.6
  webview_flutter: ^2.8.0
  shared_preferences: ^2.0.15
  permission_handler: ^10.2.0

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf
